Image card with CTA component - #8069
wellcometrust/corporate-components pull request #412
Opened 2021-02-09 12:24 UTC by DipakShrestha18

2021-02-09 16:41 UTC, creido-welly commented on src/components/ImageCardWithCTA/ImageCardWithCTA.test.tsx
> +// import React from 'react';
Is this commented out for a reason?

2021-02-09 16:49 UTC, DipakShrestha18 commented on src/components/ImageCardWithCTA/ImageCardWithCTA.test.tsx
> +// import React from 'react';
No, forgot to push it.

2021-02-09 17:29 UTC, DipakShrestha18 commented on src/components/ImageCardWithCTA/ImageCardWithCTA.test.tsx
> +// import React from 'react';
@creido-welly ready for re-review.

2021-02-09 17:41 UTC, creido-welly commented on src/components/ImageCardWithCTA/ImageCardWithCTA.tsx
> +import React from 'react';
There is a lot of duplication here, understandably so, but from a React point of view we should try to make use of _composition_ - or in other words make use of props children to create a base component which has all of the common stuff and into which the markup which is different can be nested.

e.g.

```jsx
<CardBase>
  {description && <RichText>{description}</RichText>}
</CardBase>
```

This is an oversimplification but illustrates the basics. More than happy to chat through this if you like.

Longer term we want to overhaul how listings and cards are composed as it's pretty complex and therefore not ideal. Updating both this component and ImageCard to use the same CardBase will be good step in the right direction and certainly reduce duplication.

Some more info on composition:
https://reactjs.org/docs/composition-vs-inheritance.html
https://epicreact.dev/one-react-mistake-thats-slowing-you-down/

2021-02-09 17:42 UTC, creido-welly requested changes
There is a lot of duplication here, understandably so, but from a React point of view we should try to make use of _composition_ - or in other words make use of props children to create a base component which has all of the common stuff and into which the markup which is different can be nested.

e.g.

```jsx
<CardBase>
  {description && <RichText>{description}</RichText>}
</CardBase>
```

This is an oversimplification but illustrates the basics. More than happy to chat through this if you like.

Longer term we want to overhaul how listings and cards are composed as it's pretty complex and therefore not ideal. Updating both this component and ImageCard to use the same CardBase will be good step in the right direction and certainly reduce duplication.

Some more info on composition:
https://reactjs.org/docs/composition-vs-inheritance.html
https://epicreact.dev/one-react-mistake-thats-slowing-you-down/

2021-02-09 17:49 UTC, chriddell commented
@creido-welly How about if ImageCard became the "base", and then we had ImageCardWithMetaData and ImageCardWithCTALink as the "extensions"... 🤯

2021-02-09 17:56 UTC, creido-welly commented
> @creido-welly How about if ImageCard became the "base", and then we had ImageCardWithMetaData and ImageCardWithCTALink as the "extensions"...

Sure if it makes sense to do that

2021-02-10 09:19 UTC, DipakShrestha18 commented
> > @creido-welly How about if ImageCard became the "base", and then we had ImageCardWithMetaData and ImageCardWithCTALink as the "extensions"...
> 
> Sure if it makes sense to do that. ImageCard as it stands is effectively ImageCardWithMetaData.

Do you mean extending the existing component?

2021-02-10 09:25 UTC, chriddell commented
Easiest way to think about it is probably:

- Renaming ImageCard -> ImageCardWithMetaData
- Copying all of the code from ImageCardWithMetaData to a new component: ImageCard
- Refactoring ImageCard to:
  - remove the parts which are unique to ImageCardWithMetaData and ImageCardWithCTALink 
  - add a `children` prop
- Refactoring ImageCardWithMetaData and ImageCardWithCTALink to use ImageCard and passing unique parts as `children`


Basically we would have something similar to*:

```js
const ImageCard = ({ children, ...otherProps }) => (
  <article className="c-image-card">
    <figure className="c-image-card__img">
      <img src={src} />
    </figure>
    {children}
  </article>
);

const ImageCardWithMetaData = ({ props }) => (
  <ImageCard>
    <div className="c-image-card__meta">
      <p>{props.date}</p>
      <p>{props.author}</p>
    <div>
  </ImageCard>
);

const ImageCardWithCTALink = ({ props }) => (
  <ImageCard>
    <a className="c-image-card__cta" href={props.href}>
  </ImageCard>
);
```

*this is VERY simplified

2021-02-10 09:37 UTC, DipakShrestha18 commented
Should it make sense to work that as separate job? It feels like we're side tracking as Yssy wants to get this component out this sprint. What's your view?

I can create a ticket for this and work on it next week.

2021-02-10 10:07 UTC, creido-welly commented
@DipakShrestha18 since time is short I have no objection as long as it does get done

2021-02-10 10:29 UTC, creido-welly approved these changes

2021-02-10 11:00 UTC, DipakShrestha18 commented
I have create github ticket for refactoring and consistent naming. 
https://github.com/wellcometrust/corporate/issues/8108

2021-02-10 11:13 UTC, merged