Bug/refactoring stats card fact card
wellcometrust/corporate-components pull request #426
Opened 2021-02-19 15:50 UTC by DipakShrestha18

2021-02-19 17:43 UTC, chriddell requested changes
Code looks good, but... can we name the FE component `FactCard` and drop the `WithHyperlink`? Reasons being...

- we do not have two variants `FactCard` and `FactCardWithHyperlink`
- `WithHyperlink` is fairly meaningless (the term "Hyperlink" is deprecated and doesn't tend to be used any more)
- the relationship between `FactCard` and `fact_card_with_hyperlink` is made explicit elsewhere in the code, so people are free to use either term and the relationship is visible
- it is what I proposed here https://github.com/wellcometrust/corporate/issues/8082#issuecomment-774061301 (this is the least important, really)

2021-02-19 17:46 UTC, chriddell reviewed
Sorry, another annoying point... the branch name should have a ticket number on the end. Also, just a thought - I don't think this is a `bug` branch, nothing is broken (it's just that we use the wrong names).

I think it should be a feature, so

`feature/refactoring-statistic-card-to-fact-card-#8082`

2021-02-22 14:36 UTC, creido-welly commented on src/components/FactCard/FactCard.tsx
> +export const FactCardProps = ({
You have duplication of the type `FactCardProps` here.  I'm guessing this is a find and replace oversight. It should be `FactCard`.

2021-02-22 14:37 UTC, creido-welly commented on src/components/FactCard/FactCard.tsx
> +export default FactCardProps;
See comment on line 16 - default export should be `FactCard` to match

2021-02-22 15:17 UTC, DipakShrestha18 commented on src/components/FactCard/FactCard.tsx
> +export const FactCardProps = ({
You're right find and replace. 

Re-review please.

2021-02-22 16:11 UTC, creido-welly approved these changes

2021-02-22 17:02 UTC, DipakShrestha18 commented
@chriddell Not sure what's your CR is in this. It's not allowing me to merge this PR.

2021-02-23 10:14 UTC, chriddell commented
This is mostly fine now, though the branch name should have the ticket number on the end.

Can you check out a new branch (or rename this one - not sure if that's actually possible...):

```feature/refactoring-statistic-card-fact-card-#<ticketNumber>```

2021-02-23 11:21 UTC, closed without merging